# Generated by Django 5.0.1 on 2024-02-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_no',
            field=models.TextField(),
        ),
    ]
