# Generated by Django 5.0.1 on 2024-02-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('place', models.TextField(max_length=200)),
                ('paytype', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ['item', 'price', 'place', 'paytype'],
            },
        ),
    ]
