# Generated by Django 5.0.1 on 2024-02-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
